# Usage:
    #   docker-compose up --force-recreate
version: '3'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
      - 4445:4445
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/London"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET

    healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4444"]
            interval: 10s
            timeout: 10s
            retries: 10

  mvnboxbuild:
    depends_on:
      - zalenium
    container_name: mvnbox
    build: .

  mvnbox:
    depends_on:
      - mvnboxbuild
      - zalenium
    image: javacucumberframework_mvnboxbuild